### ISSUE TITLE
Redirect to Success Page not work 

### ISSUE THREAD

**Issue by alan-qbasic** [ibrahimlawal/magento2-Profibro_Paystack#10]
@ibrahimlawal, @steveamaza 

    1. Magento ver. 1.9.2.4
    2. Paystack_Inline1.0.0.1
    3. PHP Version 5.6.30
    4. http://104.197.114.217/havilah/
    
![capture](https://user-images.githubusercontent.com/29778801/32717198-0af1ceca-c859-11e7-9d14-fbc30f15c2e2.PNG)

That is what i get even after a successful transaction.

Thanks!

**Comment by AwoyoToyin** [comment]
@alan-qbasic this module only works with Magento v 2.*
You might be looking for this since you are running Magento 1.*
https://github.com/PaystackHQ/paystack-magento

**Comment by alan-qbasic** [comment]
@awoyotoyin i have tried that earlier, i think the problem is coming from the webhook URL which i ought to set on my paystack  dashboard because everything is working fine asides for the redirection after successful payment.

Thanks

**Comment by steveamaza** [comment]
Hello @alan-qbasic, I explained in an email that you need to use a more recent release. Paystack_Inline1.0.0.1 is outdated. Please refer to my email and fix

**Comment by alan-qbasic** [comment]
@steveamaza i have installed 1.0.0.6 and the issue still persist.

**Comment by steveamaza** [comment]
Noted. Please email me your phone number and also open an issue on the appropriate plugin so we can tackle this @alan-qbasic

**Comment by steveamaza** [comment]
Moved to relevant repo https://github.com/PaystackHQ/paystack-magento/issues/6
