### ISSUE TITLE
Autoload Error

### ISSUE THREAD

**Issue by OlSaid** [ibrahimlawal/magento2-Profibro_Paystack#23]
Autoload error
Module 'Pstk_Paystack' from '/home/XXXXX/public_html/fashion/vendor/pstk/paystack-magento2-module' has been already defined in '/home/XXXXX/public_html/fashion/vendor/profibro/magento2-module-paystack'.

Please any suggestions as regards how this issue can be resolved? Thanks

**Comment by steveamaza** [comment]
Hi there. This is because you have the old version of the extension installed. Go to your vendor folder and delete the profibro folder and try again.

**Comment by OlSaid** [comment]
Thank you for the prompt response Steve, I have also replied to e-mail too but will just update here once again.

I have deleted the profitbro folder as recommended and right now apparently everything has dissappeared and the error is now an HTTP ERROR 500.

Please kindly look at the e-mail I sent earlier, will sincerely appreciate further guide on how this issue can be resolved.

Thank you

**Comment by OlSaid** [comment]
Thank you Steve, I saw your e-mail and sorry for the late reply. 

I have been able to finally fix the issue over here and will let you know if we have any other issues.
