### ISSUE TITLE
Plugin Installation Issue on Magento 2.3.0

### ISSUE THREAD

**Issue by Austinpowers7** [ibrahimlawal/magento2-Profibro_Paystack#31]
I have completed the following steps:

Install
Go to Magento2 root folder

Enter following command to install module:

composer require pstk/paystack-magento2-module
Wait while dependencies are updated.

but when I got to this part

Enter following commands to enable module:

php bin/magento module:enable Pstk_Paystack --clear-static-content

after entering the code I got an error message that read: Could not open input file: bin/magento

please I need assistance

**Comment by steveamaza** [comment]
Hi @Austinpowers7, can you show a screenshot of your command line? It's possible you are on the wrong working directory

**Comment by steveamaza** [comment]
Merchant has resolved issue as reported via email
