### ISSUE TITLE
Cant view the plugin after installation

### ISSUE THREAD

**Issue by donnffd** [ibrahimlawal/magento2-Profibro_Paystack#4]
I followed the steps to install the plugin on my localhost test machine but i cant view the plugin in my payment methods, its just empty, what might be the issue?

**Comment by ajepe** [comment]
It won't show if you are using php7+. This works https://github.com/matt-obell/paystack

**Comment by ibrahimlawal** [comment]
@ajepe okay I will check it out. Many thanks!

**Comment by AwoyoToyin** [comment]
@ajepe I use php7.0+ and it works fine

**Comment by nonami** [comment]
I'm not sure it has much to do with the version of PHP. For both 5.6 and 7.0 it isn't listed in my case.

**Comment by nonami** [comment]
@ibrahimlawal Seems to be an issue with magento being confused by `sortOrder` in `system.xml`. 
https://magento.stackexchange.com/questions/159776/magento-2-1-3-custom-payment-method-not-showing-while-showing-in-magento-2-1-1
https://github.com/magento/magento2/issues/7891

**Comment by ibrahimlawal** [comment]
@nonami WOW, so helpful. Thanks. Will push an update. Will do branch based updates from now on so others with non-recent magento versions can still benefit

**Comment by steveamaza** [comment]
@ibrahimlawal has this update been pushed? 🙂
