### ISSUE TITLE
Payment Not Initializing Even When Terms and Conditions Box is Checked

### ISSUE THREAD

**Issue by django101** [ibrahimlawal/magento2-Profibro_Paystack#41]
The Terms and Conditions box is checked, but the order still won't be placed. 
It works for other payment options.

<img width="942" alt="Screenshot 2019-07-29 at 2 25 18 PM" src="https://user-images.githubusercontent.com/43237102/62052271-10578180-b20d-11e9-9b33-967b55f75d39.png">

**Comment by steveamaza** [comment]
@django101 what version of the extension are you using? This was fixed in the latest update

**Comment by steveamaza** [comment]
Solved with #38
