### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by OlSaid** [ibrahimlawal/magento2-Profibro_Paystack#42]
Hello, 

Please see below.

Thanks.

**Comment by steveamaza** [comment]
At what stage did this happen? What was the last command you ran? Can you show a screenshot of the error too?

**Comment by OlSaid** [comment]
Hello,

Thank you for the updates,

Somehow we have been able to install the paystack extension on magento 2.

However, it does not redirect to success page.

Is there any recommendation you have as regards how to resolve this issue
without having to go through composer.

PS - We have tried your github process and it does not work. you might want
to check on your control environment.

Please let us know if you have any manual code recommendation to allow
redirection to success pasge possible with magento 2.

**Comment by steveamaza** [comment]
Hi there, please use composer. This is a requirement from magento
