### ISSUE TITLE
Please enter a valid email address 

### ISSUE THREAD

**Issue by Condelab** [ibrahimlawal/magento2-Profibro_Paystack#43]
i get this error (),
![image](https://user-images.githubusercontent.com/44819402/67012264-009f5900-f0e9-11e9-8de7-9c97b326926b.png)

 using Magento 2.3.3 and php 7.1 on Amazon AWS.

**Comment by steveamaza** [comment]
Hey @Condelab can you run `composer update` to get the latest version of the extension? This is an older version
